//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Languages.en_language", typeof(en_language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit a key to go back to the main menu....
        /// </summary>
        public static string backMenu {
            get {
                return ResourceManager.GetString("backMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete ! .
        /// </summary>
        public static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string completeType {
            get {
                return ResourceManager.GetString("completeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a correct save..
        /// </summary>
        public static string correctSaveChoice {
            get {
                return ResourceManager.GetString("correctSaveChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Create a new save.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE A SAVE.
        /// </summary>
        public static string createasave {
            get {
                return ResourceManager.GetString("createasave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes. Currently Saving..
        /// </summary>
        public static string currentlySave {
            get {
                return ResourceManager.GetString("currentlySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  deleted..
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE A SAVE.
        /// </summary>
        public static string deleteasave {
            get {
                return ResourceManager.GetString("deleteasave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of the destination directory :.
        /// </summary>
        public static string destinationPath {
            get {
                return ResourceManager.GetString("destinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the directory and all its content ? :
        ///1 - Yes
        ///2 - No.
        /// </summary>
        public static string destructFile {
            get {
                return ResourceManager.GetString("destructFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string differentialType {
            get {
                return ResourceManager.GetString("differentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory and destination directory need to be different.
        /// </summary>
        public static string differentPath {
            get {
                return ResourceManager.GetString("differentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Save ended..
        /// </summary>
        public static string endedSave {
            get {
                return ResourceManager.GetString("endedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when trying to delete the save :.
        /// </summary>
        public static string errorDelete {
            get {
                return ResourceManager.GetString("errorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Delete a save
        ///3 - Run a specific save
        ///4 - Run all saves
        ///5 - List every saves.
        /// </summary>
        public static string ifexist {
            get {
                return ResourceManager.GetString("ifexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to put a number..
        /// </summary>
        public static string inputSaveChoice {
            get {
                return ResourceManager.GetString("inputSaveChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language :
        ///1- English
        ///2- French .
        /// </summary>
        public static string LanguageChoice {
            get {
                return ResourceManager.GetString("LanguageChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF THE SAVES.
        /// </summary>
        public static string listallsaves {
            get {
                return ResourceManager.GetString("listallsaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE THE SAVES.
        /// </summary>
        public static string managesave {
            get {
                return ResourceManager.GetString("managesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do ?  :.
        /// </summary>
        public static string MenuDisplay {
            get {
                return ResourceManager.GetString("MenuDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory does not exist or could not be found: .
        /// </summary>
        public static string notFound {
            get {
                return ResourceManager.GetString("notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q - Quit.
        /// </summary>
        public static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit ? :
        ///1 - Yes
        ///2 - No.
        /// </summary>
        public static string quitApp {
            get {
                return ResourceManager.GetString("quitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIT EASYSAVE.
        /// </summary>
        public static string quitMenu {
            get {
                return ResourceManager.GetString("quitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUN ALL SAVES.
        /// </summary>
        public static string runallsaves {
            get {
                return ResourceManager.GetString("runallsaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUN A SAVE.
        /// </summary>
        public static string runsave {
            get {
                return ResourceManager.GetString("runsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUN A SPECIFIC SAVE.
        /// </summary>
        public static string runspecificsave {
            get {
                return ResourceManager.GetString("runspecificsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exist, please enter another name.
        /// </summary>
        public static string sameName {
            get {
                return ResourceManager.GetString("sameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save .
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the save number  :.
        /// </summary>
        public static string saveChoice {
            get {
                return ResourceManager.GetString("saveChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the list of every saves :.
        /// </summary>
        public static string saveList {
            get {
                return ResourceManager.GetString("saveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the save :.
        /// </summary>
        public static string saveName {
            get {
                return ResourceManager.GetString("saveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of save : 
        ///1- Complete
        ///2 - Differential.
        /// </summary>
        public static string saveType {
            get {
                return ResourceManager.GetString("saveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of the directory you want to save :.
        /// </summary>
        public static string sourcePath {
            get {
                return ResourceManager.GetString("sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many saves. Do you want to delete one ? :
        ///1 - Yes
        ///2 - No.
        /// </summary>
        public static string tooMuch {
            get {
                return ResourceManager.GetString("tooMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value :.
        /// </summary>
        public static string userInput {
            get {
                return ResourceManager.GetString("userInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chosed the save :.
        /// </summary>
        public static string verifySaveChoice {
            get {
                return ResourceManager.GetString("verifySaveChoice", resourceCulture);
            }
        }
    }
}
