//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class fr_language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Languages.fr_language", typeof(fr_language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur une touche pour revenir au menu principal....
        /// </summary>
        public static string backMenu {
            get {
                return ResourceManager.GetString("backMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complète ! .
        /// </summary>
        public static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complète.
        /// </summary>
        public static string completeType {
            get {
                return ResourceManager.GetString("completeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez une sauvegarde existante..
        /// </summary>
        public static string correctSaveChoice {
            get {
                return ResourceManager.GetString("correctSaveChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Créer une nouvelle sauvegarde.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRÉATION D&apos;UNE SAUVEGARDE.
        /// </summary>
        public static string createasave {
            get {
                return ResourceManager.GetString("createasave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui. L&apos;enregistrement est en cours..
        /// </summary>
        public static string currentlySave {
            get {
                return ResourceManager.GetString("currentlySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  supprimée..
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPRESSION D&apos;UNE SAUVEGARDE.
        /// </summary>
        public static string deleteasave {
            get {
                return ResourceManager.GetString("deleteasave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin destination du dossier :.
        /// </summary>
        public static string destinationPath {
            get {
                return ResourceManager.GetString("destinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer ce dossier ainsi que tout son contenu ? :
        ///1 - Oui
        ///2 - Non.
        /// </summary>
        public static string destructFile {
            get {
                return ResourceManager.GetString("destructFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différentielle.
        /// </summary>
        public static string differentialType {
            get {
                return ResourceManager.GetString("differentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les chemins de source et destination doivent être différents.
        /// </summary>
        public static string differentPath {
            get {
                return ResourceManager.GetString("differentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non. La sauvegarde est terminée..
        /// </summary>
        public static string endedSave {
            get {
                return ResourceManager.GetString("endedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la suppression de la sauvegarde :.
        /// </summary>
        public static string errorDelete {
            get {
                return ResourceManager.GetString("errorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Supprimer une sauvegarde
        ///3 - Lancer une sauvegarde spécifique
        ///4 - Lancer toutes les sauvegardes
        ///5 - Lister toutes les sauvegardes.
        /// </summary>
        public static string ifexist {
            get {
                return ResourceManager.GetString("ifexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez mettre un numéro..
        /// </summary>
        public static string inputSaveChoice {
            get {
                return ResourceManager.GetString("inputSaveChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTE DE TOUTES LES SAUVEGARDES.
        /// </summary>
        public static string listallsaves {
            get {
                return ResourceManager.GetString("listallsaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÉRER LES SAUVEGARDES.
        /// </summary>
        public static string managesave {
            get {
                return ResourceManager.GetString("managesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que voulez-vous faire ? :.
        /// </summary>
        public static string MenuDisplay {
            get {
                return ResourceManager.GetString("MenuDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La source n&apos;existe pas ou n&apos;a pas été trouvée :.
        /// </summary>
        public static string notFound {
            get {
                return ResourceManager.GetString("notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q - Quitter.
        /// </summary>
        public static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir quitter ? :
        ///1 - Oui
        ///2 - Non.
        /// </summary>
        public static string quitApp {
            get {
                return ResourceManager.GetString("quitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUITTER EASYSAVE.
        /// </summary>
        public static string quitMenu {
            get {
                return ResourceManager.GetString("quitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANCER TOUTES LES SAUVEGARDES.
        /// </summary>
        public static string runallsaves {
            get {
                return ResourceManager.GetString("runallsaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÉXECUTER UNE SAUVEGARDE.
        /// </summary>
        public static string runsave {
            get {
                return ResourceManager.GetString("runsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANCER UNE SAUVEGARDE SPÉCIFIQUE.
        /// </summary>
        public static string runspecificsave {
            get {
                return ResourceManager.GetString("runspecificsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom choisi existe déjà, merci d&apos;entrer un nouveau nom.
        /// </summary>
        public static string sameName {
            get {
                return ResourceManager.GetString("sameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde .
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez le numéro de sauvegarde de votre choix : .
        /// </summary>
        public static string saveChoice {
            get {
                return ResourceManager.GetString("saveChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voici la liste de toutes les sauvegardes :.
        /// </summary>
        public static string saveList {
            get {
                return ResourceManager.GetString("saveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la sauvegarde :.
        /// </summary>
        public static string saveName {
            get {
                return ResourceManager.GetString("saveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de sauvegarde :
        ///1 - Complète
        ///2 - Differentielle.
        /// </summary>
        public static string saveType {
            get {
                return ResourceManager.GetString("saveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin source du dossier :.
        /// </summary>
        public static string sourcePath {
            get {
                return ResourceManager.GetString("sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a trop de sauvegardes. Voulez-vous en supprimer une ? :
        ///1 - Oui
        ///2 - Non.
        /// </summary>
        public static string tooMuch {
            get {
                return ResourceManager.GetString("tooMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;il vous plaît, entrez une valeur : .
        /// </summary>
        public static string userInput {
            get {
                return ResourceManager.GetString("userInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez choisi la sauvegarde : .
        /// </summary>
        public static string verifySaveChoice {
            get {
                return ResourceManager.GetString("verifySaveChoice", resourceCulture);
            }
        }
    }
}
